import {randomUUID,createHash} from 'node:crypto';
import {Prisma,type PrismaClient} from '@prisma/client';
import {parseCertificateRenderConfig,buildCertificatePdfArtifactWithQr} from './certificate-module';
import {buildIssuedCertificateVariableValues} from './certificate-variables';
import {storeBuiltCertificateArtifact,getCertificateArtifact} from './certificate-artifact-storage';
type Tx=Prisma.TransactionClient;
export type CredentialReward={type:'BADGE'|'CERTIFICATE';issuerInstitutionId:string;credentialClass:'participation'|'completion'|'competence';badgeDefinitionId?:string;certificateDefinitionId?:string;snapshot?:Record<string,unknown>};
export async function requireGovernanceIssuer(tx:Tx,actorId:string,institutionId:string,programmeId:string,now:Date){const r=await tx.institutionRepresentation.findFirst({where:{userId:actorId,institutionId,programmeId,editionId:null,status:'ACTIVE',revokedAt:null,actionScope:{has:'MANAGE'},AND:[{OR:[{validFrom:null},{validFrom:{lte:now}}]},{OR:[{validUntil:null},{validUntil:{gt:now}}]}]}});if(!r)throw Error('GOV_ISSUER_DENIED');}
export async function prepareGovernanceRewards(tx:Tx,actorId:string,project:{institutionId:string;programmeId:string},condition:{all:Array<{field:string;op:string;value:unknown}>},rewards:unknown[],now:Date){
 const institution=await tx.institution.findUniqueOrThrow({where:{id:project.institutionId},select:{id:true,name:true}});const out:unknown[]=[];
 for(const raw of rewards){const item=raw as {type:string};if(item.type==='POINTS'){out.push(raw);continue;}const r=raw as CredentialReward;
  if(r.issuerInstitutionId!==project.institutionId)throw Error('GOV_ISSUER_DENIED');await requireGovernanceIssuer(tx,actorId,institution.id,project.programmeId,now);
  if(r.credentialClass==='competence'&&!condition.all.some(x=>x.field==='score'&&x.op==='gte'&&typeof x.value==='number'))throw Error('GOV_ASSESSMENT_REQUIRED');
  if(r.type==='BADGE'){const def=await tx.badgeDefinition.findFirst({where:{id:r.badgeDefinitionId,isActive:true}});if(!def)throw Error('GOV_BADGE_DENIED');out.push({...r,snapshot:{issuerName:institution.name,institutionId:institution.id,badgeName:def.name,verificationGrade:def.verificationGrade,category:def.category,criteria:condition,credentialClass:r.credentialClass,assurance:'SOURCE_VERIFIED_NOT_CP_INDEPENDENT_ASSESSMENT'}});}
  else if(r.type==='CERTIFICATE'){const def=await tx.certificateDefinition.findFirst({where:{id:r.certificateDefinitionId,isActive:true,template:{isActive:true},category:{isActive:true,pdfEnabled:true}},include:{template:true,category:true}});if(!def||def.approvalMode!=='auto')throw Error('GOV_CERTIFICATE_DENIED');const config={...parseCertificateRenderConfig(def.template.renderConfigJson),issuerName:institution.name};for(const image of [config.backgroundImageUrl,config.logoImageUrl,config.signatureImageUrl,config.sealImageUrl,...(config.elements??[]).filter(e=>e.kind==='IMAGE').map(e=>e.content)]){if(image&&!image.startsWith('data:image/'))throw Error('GOV_EXTERNAL_ASSET_BLOCKED');}out.push({...r,snapshot:{issuerName:institution.name,institutionId:institution.id,certificateName:def.name,certificateNameEn:def.nameEn,categoryName:({participation:'Participation / 参与',completion:'Completion / 结业',competence:'Competence / 能力'})[r.credentialClass],originalCategoryName:def.category.name,categoryNameEn:def.category.nameEn,templateId:def.templateId,templateVersion:def.template.version,renderConfigJson:config,criteria:condition,credentialClass:r.credentialClass,assurance:'SOURCE_VERIFIED_NOT_CP_INDEPENDENT_ASSESSMENT'}});}
  else throw Error('GOV_UNSUPPORTED_REWARD');
 }
 return out as Prisma.InputJsonValue;
}
export async function issueGovernanceCredential(tx:Tx,actorId:string,task:{id:string;factId:string;type:string;rewardJson:Prisma.JsonValue;fact:{binding:{userId:string};rule:{id:string;projectId:string}}},project:{institutionId:string;programmeId:string},now:Date){
 const r=task.rewardJson as unknown as CredentialReward;const snapshot=r?.snapshot;if(!r||!snapshot||r.type!==task.type||r.issuerInstitutionId!==project.institutionId)throw Error('GOV_REWARD_SNAPSHOT_DENIED');await requireGovernanceIssuer(tx,actorId,project.institutionId,project.programmeId,now);
 const issuerName=String(snapshot.issuerName);if(r.type==='BADGE'){
  const def=await tx.badgeDefinition.findFirst({where:{id:r.badgeDefinitionId,isActive:true},select:{id:true}});if(!def)throw Error('GOV_BADGE_DENIED');
  const award=await tx.badgeAward.create({data:{userId:task.fact.binding.userId,badgeDefinitionId:def.id,awardedByUserId:actorId,awardedByOrgName:issuerName,evidenceSnapshotJson:{governanceFactId:task.factId,governanceRuleVersionId:task.fact.rule.id,rewardTaskId:task.id,credentialClass:r.credentialClass,issuerInstitutionId:r.issuerInstitutionId,issuerName,badgeName:String(snapshot.badgeName),verificationGrade:String(snapshot.verificationGrade),assurance:String(snapshot.assurance)},verificationToken:null}});
  return {badgeAwardId:award.id};
 }
 const def=await tx.certificateDefinition.findFirst({where:{id:r.certificateDefinitionId,isActive:true,template:{isActive:true},category:{isActive:true,pdfEnabled:true}},select:{id:true}});if(!def)throw Error('GOV_CERTIFICATE_DENIED');
 const user=await tx.user.findUniqueOrThrow({where:{id:task.fact.binding.userId},select:{name:true}});const certificateName=String(snapshot.certificateName),categoryName=String(snapshot.categoryName);
 const verificationCode='CV-'+createHash('sha256').update('governance-certificate:'+task.id).digest('hex').slice(0,32).toUpperCase();const origin=process.env.AUTH_PUBLIC_ORIGIN??'http://localhost:3000';const verificationUrl=new URL('/verify/certificate/'+verificationCode,origin).toString();
 const values=buildIssuedCertificateVariableValues({holderName:user.name,certificateName,categoryName,issueDate:now,certificateNumber:verificationCode,verificationUrl,issuerName});
 const config=snapshot.renderConfigJson;const built=await buildCertificatePdfArtifactWithQr({holderName:user.name,certificateName,categoryName,issueDate:now,certificateNumber:verificationCode,verificationUrl,renderConfigJson:config,variableValues:values});if(built.mimeType!=='application/pdf'||!built.bytes||built.bytes.subarray(0,5).toString()!=='%PDF-')throw Error('GOV_PDF_REQUIRED');
 const storage=await storeBuiltCertificateArtifact(task.id,built);const readback=await getCertificateArtifact({provider:storage.artifactProvider as 'local'|'http',key:storage.artifactKey,sha256:storage.artifactSha256});if(readback.subarray(0,5).toString()!=='%PDF-')throw Error('GOV_PDF_REQUIRED');
 const issue=await tx.certificateIssue.create({data:{id:task.id,definitionId:def.id,userId:task.fact.binding.userId,sourceType:'GOVERNANCE_REWARD',sourceId:task.factId,status:'ISSUED',verificationCode,...storage,variableValuesJson:values,renderSnapshotJson:{schemaVersion:1,templateId:String(snapshot.templateId),templateVersion:Number(snapshot.templateVersion),renderConfigJson:config as Prisma.InputJsonValue,holderName:user.name,certificateName,categoryName,issuedAt:now.toISOString(),variableValues:values,issuerInstitutionId:r.issuerInstitutionId,issuerName,credentialClass:r.credentialClass,assurance:String(snapshot.assurance),governanceFactId:task.factId,governanceRuleVersionId:task.fact.rule.id},issuedAt:now,approvedBy:actorId,approvedAt:now,publicVisible:false}});
 return {certificateIssueId:issue.id};
}
export async function revokeGovernanceCredential(tx:Tx,grant:{badgeAwardId:string|null;certificateIssueId:string|null},actorId:string,now:Date){
 if(grant.badgeAwardId)await tx.badgeAward.update({where:{id:grant.badgeAwardId},data:{status:'REVOKED',revokedAt:now,revokeReason:'Authoritative source fact invalidated',verificationToken:null}});
 if(grant.certificateIssueId)await tx.certificateIssue.update({where:{id:grant.certificateIssueId},data:{status:'REVOKED',revokedAt:now,revokedByUserId:actorId,revocationReason:'Authoritative source fact invalidated',publicVisible:false}});
}
export async function changeGovernanceVisibility(tx:Tx,actorId:string,grantId:string,visible:boolean){const g=await tx.governanceRewardGrant.findUnique({where:{id:grantId},include:{fact:{include:{binding:true}}}});if(!g||g.userId!==actorId)throw Error('GOV_OWNER_DENIED');await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`governance:participation:${g.fact.binding.participationId}`},0))`;await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`governance:binding:${g.fact.bindingId}`},0))`;const current=await tx.governanceRewardGrant.findUniqueOrThrow({where:{id:grantId},include:{fact:true}});const decision=await tx.governanceRewardDecision.findUnique({where:{activeGrantId:current.id}});if(visible&&(current.state!=='ACTIVE'||decision?.state!=='ACTIVE'||!decision.basisFactId))throw Error('GOV_FACT_INVALIDATED');if(current.badgeAwardId)await tx.badgeAward.update({where:{id:current.badgeAwardId},data:{verificationToken:visible?randomUUID():null}});if(current.certificateIssueId)await tx.certificateIssue.update({where:{id:current.certificateIssueId},data:{publicVisible:visible}});await tx.governanceRewardGrant.update({where:{id:grantId},data:{publicVisible:visible}});return {grantId,publicVisible:visible};}
