import {createHash,randomUUID} from "node:crypto";
import {Prisma,type PrismaClient} from "@prisma/client";
import {GovernanceCommandSchema,type GovernanceCommand} from "@climate-passport/passport-contracts";
import {resolveScopedAccess} from "./programme-scope";
import {prepareGovernanceRewards,requireGovernanceIssuer,issueGovernanceCredential,revokeGovernanceCredential,changeGovernanceVisibility} from './governance-credentials';
import {matchesTypedCondition,parseTypedCondition} from "./governance-conditions";
type Tx=Prisma.TransactionClient;
export class GovernanceError extends Error {constructor(public code:string,public status=409){super(code);}}
function fail(code:string,status=409):never {throw new GovernanceError(code,status);}
function canonical(v:unknown):unknown {if(Array.isArray(v))return v.map(canonical);if(v!==null&&typeof v==='object')return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)]));return v;}
export function governanceDigest(v:unknown){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
export function governanceSubjectHash(issuer:string,audience:string,subject:string){return governanceDigest([issuer,audience,subject]);}
async function lock(tx:Tx,key:string){await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${key},0))`;}
async function userActive(tx:Tx,id:string){const u=await tx.user.findUnique({where:{id},select:{status:true,anonymizedAt:true}});if(!u||u.status!=='ACTIVE'||u.anonymizedAt)fail('GOV_USER_DENIED',403);}
async function scoped(tx:Tx,id:string,programmeId:string,action:'read'|'write'|'manage'){await userActive(tx,id);const d=await resolveScopedAccess(tx,{id},{programmeId},action);if(!d.allowed)fail('GOV_SCOPE_DENIED',403);}
async function projectFor(tx:Tx,id:string,actorId:string,action:'read'|'write'|'manage'){const p=await tx.governanceProject.findUnique({where:{id}});if(!p)fail('GOV_NOT_FOUND',404);await scoped(tx,actorId,p.programmeId,action);return p;}
async function audit(tx:Tx,actorId:string,action:string,id:string){await tx.coreAuditLog.create({data:{actorUserId:actorId,action:'governance.'+action,subjectType:'governance',subjectId:id,result:'applied'}});}
async function addTask(tx:Tx,factId:string,operation:string,points:number,type='POINTS',rewardJson?:Prisma.InputJsonValue,dependencyFactId?:string){await tx.governanceRewardTask.upsert({where:{factId_operation_type:{factId,operation,type}},create:{factId,operation,type,points,rewardJson,dependencyFactId},update:operation==='REVERSE'?{state:'PENDING',failureCode:null,nextAttemptAt:new Date()}:{}});}
async function invalidate(tx:Tx,factId:string){await tx.governanceFact.update({where:{id:factId},data:{state:'INVALIDATED'}});await tx.governanceRewardTask.updateMany({where:{factId,operation:'GRANT',state:{in:['PENDING','RETRY','BLOCKED']}},data:{state:'CANCELLED',failureCode:'FACT_INVALIDATED'}});}
async function eligibleBasis(tx:Tx,participationId:string){return tx.governanceFact.findFirst({where:{state:'ELIGIBLE',binding:{participationId}},orderBy:[{occurredAt:'asc'},{id:'asc'}]});}
async function reconcileCanonicalBasis(tx:Tx,participationId:string){
 const basis=await eligibleBasis(tx,participationId);const decisions=await tx.governanceRewardDecision.findMany({where:{participationId,activeGrantId:{not:null}}});
 for(const d of decisions){if(basis){await tx.governanceRewardDecision.update({where:{id:d.id},data:{state:'ACTIVE',basisFactId:basis.id}});continue;}
  const g=await tx.governanceRewardGrant.findUniqueOrThrow({where:{id:d.activeGrantId!}});await tx.governanceRewardDecision.update({where:{id:d.id},data:{state:'RECONCILIATION_PENDING',basisFactId:null}});await addTask(tx,g.factId,'REVERSE',g.points,g.type);
  await tx.governanceRewardGrant.update({where:{id:g.id},data:{publicVisible:false}});
  if(g.badgeAwardId)await tx.badgeAward.update({where:{id:g.badgeAwardId},data:{verificationToken:null}});
  if(g.certificateIssueId)await tx.certificateIssue.update({where:{id:g.certificateIssueId},data:{publicVisible:false}});
 }
}
async function currentQualificationConsent(tx:Tx,e:Exclude<Extract<GovernanceCommand,{action:'qualify'}>['event'],{operation:'revoke'}>,b:{userId:string;sourceRecordId:string},s:{sourceApp:string},now:Date){
 await tx.$queryRaw`SELECT id FROM consent_records WHERE id=${e.consent.receiptId} FOR SHARE`;
 const c=await tx.consentRecord.findUnique({where:{id:e.consent.receiptId}});const at=new Date(e.occurredAt);
 if(!c||c.status!=='ACTIVE'||c.subjectUserId!==b.userId||c.grantorUserId!==b.userId||c.guardianUserId||c.version!==e.consent.version||c.purpose!=='reward_qualification'||c.channel!==s.sourceApp||c.objectType!=='governance_outcome'||c.objectId!==b.sourceRecordId||c.programmeId!==null||c.createdAt.getTime()!==Date.parse(e.consent.grantedAt)||c.createdAt>at||c.validFrom>at||c.validFrom>now||(c.validUntil&&(c.validUntil<=now||c.validUntil<=at)))fail('GOV_CONSENT_DENIED',403);
}
export async function executeGovernance(prisma:PrismaClient,actorId:string,raw:unknown,now=new Date()){
 const parsed=GovernanceCommandSchema.safeParse(raw);if(!parsed.success)fail('GOV_INVALID_REQUEST',400);const c=parsed.data;
 if(c.action==='process')return processGovernanceReward(prisma,actorId,c.projectId,c.taskId,now);
 return prisma.$transaction(async tx=>{
  if(c.action==='visibility'){await userActive(tx,actorId);const result=await changeGovernanceVisibility(tx,actorId,c.grantId,c.publicVisible);await audit(tx,actorId,'visibility',c.grantId);return result;}
  if(c.action==='register'){
   await scoped(tx,actorId,c.programmeId,'write');const rep=await tx.institutionRepresentation.findFirst({where:{userId:actorId,institutionId:c.institutionId,programmeId:c.programmeId,editionId:null,status:'ACTIVE',revokedAt:null,actionScope:{has:'MANAGE'},AND:[{OR:[{validFrom:null},{validFrom:{lte:now}}]},{OR:[{validUntil:null},{validUntil:{gt:now}}]}]}});if(!rep)fail('GOV_INSTITUTION_DENIED',403);
   if(c.activityId){const m=await tx.sourceObjectMapping.findMany({where:{activityId:c.activityId,applyStatus:'ACTIVE'},select:{programmeId:true}});if(m.some(x=>x.programmeId!==c.programmeId))fail('GOV_SCOPE_DENIED',403);const a=await tx.activity.findUnique({where:{id:c.activityId},select:{organizerUserId:true}});if(!a||a.organizerUserId!==actorId)fail('GOV_ACTIVITY_DENIED',403);}
   const p=await tx.governanceProject.create({data:{code:'CPU-'+randomUUID(),programmeId:c.programmeId,institutionId:c.institutionId,activityId:c.activityId,kind:c.kind,title:c.title,createdByUserId:actorId}});await audit(tx,actorId,'register',p.id);return {project:p};
  }
  if(c.action==='source'){
   await lock(tx,'governance:project:'+c.projectId);const p=await projectFor(tx,c.projectId,actorId,'write');if(p.status!=='DRAFT')fail('GOV_FROZEN');const client=await tx.channelClient.findUnique({where:{id:c.channelClientId},select:{programmeId:true,isActive:true}});if(!client?.isActive||client.programmeId!==p.programmeId)fail('GOV_SOURCE_DENIED',403);await scoped(tx,c.verifierUserId,p.programmeId,'write');const s=await tx.governanceSource.create({data:{projectId:p.id,channelClientId:c.channelClientId,sourceApp:c.sourceApp,sourceAuthority:c.sourceAuthority,externalUnitId:c.externalUnitId,issuer:c.issuer,rpAudience:c.rpAudience,verifierUserId:c.verifierUserId}});await audit(tx,actorId,'source',s.id);return {source:s};
  }
  if(c.action==='binding'){
   const s=await tx.governanceSource.findUnique({where:{id:c.sourceId}});if(!s)fail('GOV_NOT_FOUND',404);const p=await projectFor(tx,s.projectId,actorId,'manage');await userActive(tx,c.userId);await lock(tx,'governance:entry:'+p.id+':'+c.userId);
   let participation=await tx.governanceParticipation.findUnique({where:{projectId_userId:{projectId:p.id,userId:c.userId}}});
   if(participation){if(participation.ruleVersionId!==c.ruleVersionId)fail('GOV_PARTICIPATION_RULE_PINNED');}
   else {const rule=await tx.governanceRuleVersion.findUnique({where:{id:c.ruleVersionId}});if(!rule||rule.projectId!==p.id||rule.status!=='PUBLISHED'||p.status!=='PUBLISHED'||rule.validUntil<=now)fail('GOV_RULE_NOT_EFFECTIVE');participation=await tx.governanceParticipation.create({data:{projectId:p.id,userId:c.userId,ruleVersionId:rule.id,createdByUserId:actorId}});}
   const b=await tx.governanceBinding.create({data:{sourceId:s.id,userId:c.userId,participationId:participation.id,subjectHash:governanceSubjectHash(s.issuer,s.rpAudience,c.subject),sourceRecordId:c.sourceRecordId,verificationRef:c.verificationRef}});await audit(tx,actorId,'binding',b.id);return {binding:{id:b.id,sourceRecordId:b.sourceRecordId,participationId:participation.id,ruleVersionId:participation.ruleVersionId}};
  }
  if(c.action==='rule'){
   await lock(tx,'governance:project:'+c.projectId);const p=await projectFor(tx,c.projectId,actorId,'write');if(p.status==='RETIRED')fail('GOV_RETIRED');if(new Date(c.validUntil)<=new Date(c.validFrom))fail('GOV_INVALID_WINDOW',400);parseTypedCondition(c.condition);const last=await tx.governanceRuleVersion.findFirst({where:{projectId:p.id},orderBy:{version:'desc'}});if(c.version!==(last?.version??0)+1)fail('GOV_VERSION_CONFLICT');const rewards=await prepareGovernanceRewards(tx,actorId,p,c.condition,c.rewards,now);const r=await tx.governanceRuleVersion.create({data:{projectId:p.id,version:c.version,conditionJson:c.condition,rewardsJson:rewards,validFrom:new Date(c.validFrom),validUntil:new Date(c.validUntil),createdByUserId:actorId,digest:governanceDigest({...c,rewards})}});await audit(tx,actorId,'rule',r.id);return {rule:r};
  }
  if(c.action==='transition'){
   await lock(tx,'governance:project:'+c.projectId);const p=await projectFor(tx,c.projectId,actorId,'manage');const r=c.ruleVersionId?await tx.governanceRuleVersion.findFirst({where:{id:c.ruleVersionId,projectId:p.id}}):null;if(c.ruleVersionId&&!r)fail('GOV_NOT_FOUND',404);const target=r??p;const statuses={approve:['DRAFT','APPROVED'],publish:['APPROVED','PUBLISHED'],retire:['PUBLISHED','RETIRED']} as const;const [before,after]=statuses[c.transition];if(target.status===after)return {id:target.id,status:after,deduplicated:true};if(target.status!==before)fail('GOV_STATE_CONFLICT');if(c.transition==='approve'&&target.createdByUserId===actorId)fail('GOV_SEPARATION_OF_DUTIES',403);if(c.transition==='approve'&&r&&(r.rewardsJson as Array<{type:string}>).some(x=>x.type!=='POINTS'))await requireGovernanceIssuer(tx,actorId,p.institutionId,p.programmeId,now);
   if(c.transition==='publish'){if(r&&p.status!=='PUBLISHED')fail('GOV_PROJECT_NOT_PUBLISHED');if(r&&r.validUntil<=now)fail('GOV_INVALID_WINDOW',400);if(!r&&!await tx.governanceSource.count({where:{projectId:p.id}}))fail('GOV_SOURCE_REQUIRED');}
   const data={status:after,...(c.transition==='approve'?{approvedByUserId:actorId,approvedAt:now}:{}),...(c.transition==='publish'?{publishedAt:now}:{})};if(r)await tx.governanceRuleVersion.update({where:{id:r.id},data});else await tx.governanceProject.update({where:{id:p.id},data});await audit(tx,actorId,c.transition,target.id);return {id:target.id,status:after};
  }
  if(c.action==='retry'){
   const p=await projectFor(tx,c.projectId,actorId,'manage');const t=await tx.governanceRewardTask.findUnique({where:{id:c.taskId},include:{fact:{include:{rule:true,binding:true}}}});if(!t||t.fact.rule.projectId!==p.id)fail('GOV_NOT_FOUND',404);if(!['RETRY','BLOCKED'].includes(t.state))fail('GOV_STATE_CONFLICT');if(t.operation==='GRANT'&&t.fact.state!=='ELIGIBLE')fail('GOV_FACT_INVALIDATED');await tx.governanceRewardTask.update({where:{id:t.id},data:{state:'PENDING',attempts:0,failureCode:null,nextAttemptAt:now}});await audit(tx,actorId,'retry',t.id);return {taskId:t.id,state:'PENDING'};
  }
  if(c.action==='qualify'){
   const e=c.event;const entry=await tx.governanceBinding.findUnique({where:{id:e.bindingId},select:{participationId:true}});if(!entry?.participationId)fail('GOV_BINDING_DENIED',403);await lock(tx,'governance:participation:'+entry.participationId);await lock(tx,'governance:binding:'+e.bindingId);const b=await tx.governanceBinding.findUnique({where:{id:e.bindingId},include:{source:{include:{client:true}},participation:true}});if(!b)fail('GOV_NOT_FOUND',404);const s=b.source;const project=await tx.governanceProject.findUniqueOrThrow({where:{id:s.projectId}});await scoped(tx,actorId,project.programmeId,'write');if(e.operation!=='revoke'&&s.client.programmeId!==project.programmeId)fail('GOV_SOURCE_DENIED',403);if(actorId!==s.verifierUserId)fail('GOV_VERIFIER_DENIED',403);if(e.operation!=='revoke')await userActive(tx,b.userId);if((e.operation!=='revoke'&&!s.client.isActive)||s.issuer!==e.identity.issuer||b.subjectHash!==governanceSubjectHash(s.issuer,s.rpAudience,e.identity.subject)||b.sourceRecordId!==e.sourceRecord.id)fail('GOV_BINDING_DENIED',403);
   const digest=governanceDigest(e);const old=await tx.governanceFact.findUnique({where:{bindingId_eventId:{bindingId:b.id,eventId:e.eventId}}});if(old){if(old.digest!==digest)fail('GOV_IMMUTABLE_CONFLICT');return {qualificationAccepted:true,factId:old.id,eligibility:old.state.toLowerCase(),historical:true,rewardSuccess:false};}
   if(b.terminalRevoked)fail('GOV_TERMINAL');if(e.sourceRecord.version!==b.currentVersion+1||(!b.currentVersion&&e.operation!=='upsert')||(b.currentVersion&&(e.operation==='upsert'||e.supersedesEventId!==b.headEventId)))fail('GOV_VERSION_CONFLICT');if(Date.parse(e.occurredAt)>now.getTime()+300000)fail('GOV_TIME_DENIED',400);
   const r=await tx.governanceRuleVersion.findUnique({where:{id:e.ruleVersionId},include:{project:true}});if(!r||r.projectId!==s.projectId||!b.participation||b.participation.ruleVersionId!==r.id)fail('GOV_RULE_DENIED',403);const prior=b.headEventId?await tx.governanceFact.findUniqueOrThrow({where:{bindingId_eventId:{bindingId:b.id,eventId:b.headEventId}}}):null;
   if(prior&&prior.ruleVersionId!==r.id)fail('GOV_RULE_VERSION_PINNED');let eligible=false;
   if(e.operation!=='revoke'){
    if(!['PUBLISHED','RETIRED'].includes(r.status)||!['PUBLISHED','RETIRED'].includes(r.project.status)||!r.publishedAt||new Date(e.occurredAt)<b.participation.createdAt||new Date(e.occurredAt)<r.publishedAt||new Date(e.occurredAt)<r.validFrom||new Date(e.occurredAt)>=r.validUntil)fail('GOV_RULE_NOT_EFFECTIVE');if((s.sourceApp==='gca'&&(e.data.kind!=='learning_completion'||e.data.status!=='completed'))||(s.sourceApp==='fs'&&(e.data.kind!=='approved_private_evidence'||e.data.status!=='accepted')))fail('GOV_FACT_KIND_DENIED',400);
    await currentQualificationConsent(tx,e,b,s,now);eligible=matchesTypedCondition(r.conditionJson,e.data);
   }
   if(prior)await invalidate(tx,prior.id);
   const f=await tx.governanceFact.create({data:{bindingId:b.id,ruleVersionId:r.id,eventId:e.eventId,sourceVersion:e.sourceRecord.version,operation:e.operation,supersedesEventId:e.operation==='upsert'?null:e.supersedesEventId,occurredAt:new Date(e.occurredAt),digest,factsJson:e.operation==='revoke'?Prisma.DbNull:e.data,consentId:e.operation==='revoke'?null:e.consent.receiptId,state:e.operation==='revoke'?'REVOKED':eligible?'ELIGIBLE':'INELIGIBLE'}});
   await tx.governanceBinding.update({where:{id:b.id},data:{currentVersion:e.sourceRecord.version,headEventId:e.eventId,terminalRevoked:e.operation==='revoke'}});
   if(eligible){const rewards=r.rewardsJson as Array<{type:string;points?:number}>;for(const reward of rewards)await addTask(tx,f.id,'GRANT',reward.type==='POINTS'?reward.points!:0,reward.type,reward as Prisma.InputJsonValue,prior?.id);}
   await reconcileCanonicalBasis(tx,b.participation.id);await audit(tx,actorId,'fact_'+e.operation,f.id);return {qualificationAccepted:true,factId:f.id,eligibility:f.state.toLowerCase(),historical:false,rewardSuccess:false};
  }
  fail('GOV_INVALID_REQUEST',400);
 }).catch(error=>{if(error instanceof Error&&/^GOV_[A-Z_]+$/.test(error.message)&&!(error instanceof GovernanceError))throw new GovernanceError(error.message,error.message.endsWith('DENIED')?403:409);throw error;});
}
/** Worker commits grant claim, balance, signed ledger and task success atomically. */
export async function processGovernanceReward(prisma:PrismaClient,actorId:string,projectId:string,taskId:string,now=new Date()){
 try{return await prisma.$transaction(async tx=>{
  const first=await tx.governanceRewardTask.findUnique({where:{id:taskId},include:{fact:{include:{binding:true}}}});if(!first)fail('GOV_NOT_FOUND',404);if(!first.fact.binding.participationId)fail('GOV_BINDING_DENIED',403);await lock(tx,'governance:participation:'+first.fact.binding.participationId);await lock(tx,'governance:binding:'+first.fact.bindingId);const t=await tx.governanceRewardTask.findUniqueOrThrow({where:{id:taskId},include:{fact:{include:{binding:true,rule:true}}}});if(t.fact.rule.projectId!==projectId)fail('GOV_NOT_FOUND',404);const project=await projectFor(tx,projectId,actorId,'manage');if(t.state==='SUCCEEDED'||t.state==='CANCELLED')return {taskId,state:t.state,deduplicated:true};if(!['PENDING','RETRY'].includes(t.state)||t.nextAttemptAt>now)fail('GOV_TASK_NOT_READY');await lock(tx,'governance:user:'+t.fact.binding.userId);
  if(t.operation==='GRANT'){
   if(t.fact.state!=='ELIGIBLE'){await tx.governanceRewardTask.update({where:{id:taskId},data:{state:'CANCELLED'}});return {taskId,state:'CANCELLED'};}
   const participationId=t.fact.binding.participationId!;const decision=await tx.governanceRewardDecision.upsert({where:{participationId_type:{participationId,type:t.type}},create:{participationId,type:t.type},update:{}});
   if(decision.activeGrantId){const basis=await eligibleBasis(tx,participationId);if(basis){await tx.governanceRewardDecision.update({where:{id:decision.id},data:{state:'ACTIVE',basisFactId:basis.id}});await tx.governanceRewardTask.update({where:{id:taskId},data:{state:'SUCCEEDED',failureCode:'CANONICAL_AWARD_ALREADY_ACTIVE'}});return {taskId,state:'SUCCEEDED',rewardSuccess:true,deduplicated:true};}fail('GOV_DEPENDENCY_PENDING');}
   if(t.fact.consentId){await tx.$queryRaw`SELECT id FROM consent_records WHERE id=${t.fact.consentId} FOR SHARE`;const consent=await tx.consentRecord.findUnique({where:{id:t.fact.consentId}});if(!consent||consent.status!=='ACTIVE'||(consent.validUntil&&consent.validUntil<=now)){await tx.governanceRewardTask.update({where:{id:taskId},data:{state:'BLOCKED',failureCode:'QUALIFICATION_CONSENT_WITHDRAWN'}});return {taskId,state:'BLOCKED',failureCode:'QUALIFICATION_CONSENT_WITHDRAWN'};}}
   await userActive(tx,t.fact.binding.userId);const existing=await tx.governanceRewardGrant.findUnique({where:{factId_type:{factId:t.factId,type:t.type}}});if(!existing){let references:{pointTransactionId?:string;badgeAwardId?:string;certificateIssueId?:string};if(t.type==='POINTS'){const ledger=await tx.pointTransaction.create({data:{userId:t.fact.binding.userId,points:t.points,type:'GOVERNANCE_REWARD',description:'Approved rule '+t.fact.rule.id+'; fact '+t.factId,createdBy:actorId}});await tx.user.update({where:{id:t.fact.binding.userId},data:{points:{increment:t.points}}});references={pointTransactionId:ledger.id};}else if(t.type==='BADGE'||t.type==='CERTIFICATE'){references=await issueGovernanceCredential(tx,actorId,{...t,rewardJson:t.rewardJson!},project,now);}else fail('GOV_UNSUPPORTED_REWARD');const granted=await tx.governanceRewardGrant.create({data:{factId:t.factId,userId:t.fact.binding.userId,type:t.type,points:t.points,...references}});await tx.governanceRewardDecision.update({where:{id:decision.id},data:{state:'ACTIVE',activeGrantId:granted.id,basisFactId:t.factId}});}
  }else if(t.operation==='REVERSE'){
   const g=await tx.governanceRewardGrant.findUnique({where:{factId_type:{factId:t.factId,type:t.type}}});if(g?.state==='ACTIVE'){const decision=await tx.governanceRewardDecision.findUnique({where:{activeGrantId:g.id}});if(!decision)fail('GOV_DECISION_DENIED');const basis=await eligibleBasis(tx,decision.participationId);if(basis){await tx.governanceRewardDecision.update({where:{id:decision.id},data:{state:'ACTIVE',basisFactId:basis.id}});await tx.governanceRewardTask.update({where:{id:taskId},data:{state:'CANCELLED',failureCode:'ALTERNATIVE_VALID_BASIS'}});return {taskId,state:'CANCELLED',failureCode:'ALTERNATIVE_VALID_BASIS'};}let reversalTransactionId:string|undefined;if(g.type==='POINTS'){const ledger=await tx.pointTransaction.create({data:{userId:g.userId,points:-g.points,type:'GOVERNANCE_REVERSAL',description:'Reversal of '+g.pointTransactionId+'; invalidated fact '+t.factId,createdBy:actorId}});await tx.user.update({where:{id:g.userId},data:{points:{decrement:g.points}}});reversalTransactionId=ledger.id;}else await revokeGovernanceCredential(tx,g,actorId,now);await tx.governanceRewardGrant.update({where:{id:g.id},data:{state:'REVERSED',reversalTransactionId,reversedAt:now,publicVisible:false}});await tx.governanceRewardDecision.update({where:{id:decision.id},data:{state:'REVERSED',activeGrantId:null,basisFactId:null}});}
  }else fail('GOV_UNSUPPORTED_REWARD');
  await tx.governanceRewardTask.update({where:{id:taskId},data:{state:'SUCCEEDED',attempts:{increment:1},failureCode:null}});await audit(tx,actorId,'reward_'+t.operation.toLowerCase(),taskId);return {taskId,state:'SUCCEEDED',rewardSuccess:true};
 },{timeout:120000,maxWait:10000});}catch(error){
  // Unauthorized/not-ready requests must never mutate task retries. Transaction failures roll back all reward writes.
  if(error instanceof GovernanceError)throw error;if(error instanceof Error&&['GOV_ISSUER_DENIED','GOV_OWNER_DENIED','GOV_FACT_INVALIDATED'].includes(error.message))throw new GovernanceError(error.message,403);
  const t=await prisma.governanceRewardTask.findUnique({where:{id:taskId},include:{fact:{include:{rule:true}}}});if(t&&t.fact.rule.projectId===projectId){await prisma.$transaction(async tx=>{await projectFor(tx,projectId,actorId,'manage');await tx.governanceRewardTask.updateMany({where:{id:taskId,state:{in:['PENDING','RETRY']},attempts:t.attempts},data:{state:t.attempts>=7?'BLOCKED':'RETRY',attempts:{increment:1},nextAttemptAt:new Date(now.getTime()+Math.min(60000*2**t.attempts,3600000)),failureCode:'TRANSACTION_FAILED'}});});}fail('GOV_REWARD_RETRY',503);
 }
}
export async function readGovernance(prisma:PrismaClient,actorId:string,projectId:string){return prisma.$transaction(async tx=>{const p=await projectFor(tx,projectId,actorId,'read');const rules=await tx.governanceRuleVersion.findMany({where:{projectId}});const sources=await tx.governanceSource.findMany({where:{projectId},select:{id:true,sourceApp:true,externalUnitId:true}});const tasks=await tx.governanceRewardTask.findMany({where:{fact:{rule:{projectId}}},select:{id:true,state:true,operation:true,type:true,points:true,attempts:true,failureCode:true,factId:true,nextAttemptAt:true},orderBy:{createdAt:'desc'},take:100});return {project:p,rules,sources,tasks};});}
