-- Additive, local-only Phase 4 bounded activity community. No global community surfaces.
CREATE TYPE "ActivityCommunityMode" AS ENUM ('OPEN', 'READ_ONLY', 'CLOSED');
CREATE TYPE "ActivityCommunityMemberRole" AS ENUM ('MEMBER', 'MODERATOR');
CREATE TYPE "ActivityCommunityMemberStatus" AS ENUM ('ACTIVE', 'SUSPENDED');
CREATE TYPE "ActivityCommunityPostKind" AS ENUM ('UPDATE', 'DISCUSSION');
CREATE TYPE "ActivityCommunityContentStatus" AS ENUM ('PENDING', 'PUBLISHED', 'REJECTED', 'HIDDEN');
CREATE TABLE "activity_communities" ("id" TEXT NOT NULL, "activityId" TEXT NOT NULL, "mode" "ActivityCommunityMode" NOT NULL DEFAULT 'OPEN', "premoderated" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "activity_communities_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "activity_communities_activityId_key" ON "activity_communities"("activityId");
CREATE TABLE "activity_community_members" ("id" TEXT NOT NULL, "communityId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "ActivityCommunityMemberRole" NOT NULL DEFAULT 'MEMBER', "status" "ActivityCommunityMemberStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "activity_community_members_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "activity_community_members_communityId_userId_key" ON "activity_community_members"("communityId", "userId"); CREATE INDEX "activity_community_members_userId_status_idx" ON "activity_community_members"("userId", "status");
CREATE TABLE "activity_community_posts" ("id" TEXT NOT NULL, "communityId" TEXT NOT NULL, "authorUserId" TEXT NOT NULL, "kind" "ActivityCommunityPostKind" NOT NULL, "body" TEXT NOT NULL, "status" "ActivityCommunityContentStatus" NOT NULL DEFAULT 'PENDING', "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "activity_community_posts_pkey" PRIMARY KEY ("id")); CREATE INDEX "activity_community_posts_communityId_status_createdAt_idx" ON "activity_community_posts"("communityId", "status", "createdAt");
CREATE TABLE "activity_community_comments" ("id" TEXT NOT NULL, "postId" TEXT NOT NULL, "authorUserId" TEXT NOT NULL, "body" TEXT NOT NULL, "status" "ActivityCommunityContentStatus" NOT NULL DEFAULT 'PENDING', "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "activity_community_comments_pkey" PRIMARY KEY ("id")); CREATE INDEX "activity_community_comments_postId_status_createdAt_idx" ON "activity_community_comments"("postId", "status", "createdAt");
CREATE TABLE "activity_community_reports" ("id" TEXT NOT NULL, "reporterUserId" TEXT NOT NULL, "postId" TEXT, "commentId" TEXT, "reason" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "activity_community_reports_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "activity_community_reports_reporterUserId_postId_key" ON "activity_community_reports"("reporterUserId", "postId"); CREATE UNIQUE INDEX "activity_community_reports_reporterUserId_commentId_key" ON "activity_community_reports"("reporterUserId", "commentId");
ALTER TABLE "activity_communities" ADD CONSTRAINT "activity_communities_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "activities"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "activity_community_members" ADD CONSTRAINT "activity_community_members_communityId_fkey" FOREIGN KEY ("communityId") REFERENCES "activity_communities"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "activity_community_members_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "activity_community_posts" ADD CONSTRAINT "activity_community_posts_communityId_fkey" FOREIGN KEY ("communityId") REFERENCES "activity_communities"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "activity_community_posts_authorUserId_fkey" FOREIGN KEY ("authorUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "activity_community_comments" ADD CONSTRAINT "activity_community_comments_postId_fkey" FOREIGN KEY ("postId") REFERENCES "activity_community_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "activity_community_comments_authorUserId_fkey" FOREIGN KEY ("authorUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "activity_community_reports" ADD CONSTRAINT "activity_community_reports_reporterUserId_fkey" FOREIGN KEY ("reporterUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "activity_community_reports_postId_fkey" FOREIGN KEY ("postId") REFERENCES "activity_community_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT "activity_community_reports_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "activity_community_comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
