import { NextResponse } from "next/server";
import { ExternalLearningAdminListQuerySchema, ExternalLearningCourseMappingPayloadSchema, ExternalLearningCourseMappingUpdateSchema } from "@climate-passport/passport-contracts";
import { getCurrentUser } from "@/lib/server/auth";
import { getPrismaClient } from "@/lib/server/prisma";
import { getRequestAuditContext, writeCoreAuditLog } from "@/lib/server/audit";
import { sha256Reference } from "@/lib/server/external-learning";
async function requireAdmin() { const user = await getCurrentUser(); return user?.role === "ADMIN" ? user : null; }
export async function GET(request: Request) { if (!await requireAdmin()) return NextResponse.json({ error: { code: "UNAUTHENTICATED" } }, { status: 403 }); const query = ExternalLearningAdminListQuerySchema.safeParse(Object.fromEntries(new URL(request.url).searchParams)); if (!query.success) return NextResponse.json({ error: { code: "INVALID_REQUEST" } }, { status: 400 }); const prisma = getPrismaClient(); if (!prisma) return NextResponse.json({ error: { code: "SERVICE_UNAVAILABLE" } }, { status: 503 }); const rows = await prisma.externalLearningCourseMapping.findMany({ take: query.data.limit + 1, ...(query.data.cursor ? { cursor: { id: query.data.cursor }, skip: 1 } : {}), orderBy: { id: "asc" } }); return NextResponse.json({ items: rows.slice(0, query.data.limit), nextCursor: rows.length > query.data.limit ? rows[query.data.limit]?.id : null }); }
export async function POST(request: Request) { const admin = await requireAdmin(); if (!admin) return NextResponse.json({ error: { code: "UNAUTHENTICATED" } }, { status: 403 }); const body = ExternalLearningCourseMappingPayloadSchema.safeParse(await request.json().catch(() => null)); if (!body.success) return NextResponse.json({ error: { code: "INVALID_REQUEST" } }, { status: 400 }); const prisma = getPrismaClient(); if (!prisma) return NextResponse.json({ error: { code: "SERVICE_UNAVAILABLE" } }, { status: 503 }); const [provider, program, activity] = await Promise.all([prisma.externalLearningProvider.findUnique({ where: { id: body.data.providerId }, select: { status: true } }), body.data.learningExperienceProgramId ? prisma.learningExperienceProgram.findUnique({ where: { id: body.data.learningExperienceProgramId }, select: { id: true } }) : null, body.data.activityId ? prisma.activity.findUnique({ where: { id: body.data.activityId }, select: { id: true } }) : null]); if (provider?.status !== "ACTIVE" || (body.data.learningExperienceProgramId && !program) || (body.data.activityId && !activity)) return NextResponse.json({ error: { code: "INVALID_REQUEST" } }, { status: 400 }); try { const mapping = await prisma.externalLearningCourseMapping.create({ data: { providerId: body.data.providerId, externalCourseHash: sha256Reference(body.data.externalCourseId), learningExperienceProgramId: body.data.learningExperienceProgramId, activityId: body.data.activityId, status: body.data.status } }); await writeCoreAuditLog({ actorUserId: admin.id, action: "EXTERNAL_LEARNING_COURSE_MAPPING_CREATED", subjectType: "ExternalLearningCourseMapping", subjectId: mapping.id, result: "SUCCESS", metadataJson: { providerId: mapping.providerId, status: mapping.status, target: mapping.learningExperienceProgramId ? "PROGRAM" : "ACTIVITY" }, ...getRequestAuditContext(request) }); return NextResponse.json({ mapping }, { status: 201 }); } catch { return NextResponse.json({ error: { code: "INVALID_REQUEST" } }, { status: 409 }); } }
export async function PATCH(request: Request) { const admin = await requireAdmin(); if (!admin) return NextResponse.json({ error: { code: "UNAUTHENTICATED" } }, { status: 403 }); const body = ExternalLearningCourseMappingUpdateSchema.safeParse(await request.json().catch(() => null)); if (!body.success) return NextResponse.json({ error: { code: "INVALID_REQUEST" } }, { status: 400 }); const prisma = getPrismaClient(); if (!prisma) return NextResponse.json({ error: { code: "SERVICE_UNAVAILABLE" } }, { status: 503 }); const existing = await prisma.externalLearningCourseMapping.findUnique({ where: { id: body.data.id }, include: { provider: { select: { status: true } } } }); if (!existing || (body.data.action === "ACTIVATE" && existing.provider.status !== "ACTIVE")) return NextResponse.json({ error: { code: "INVALID_REQUEST" } }, { status: 400 }); const mapping = await prisma.externalLearningCourseMapping.update({ where: { id: existing.id }, data: { status: body.data.action === "ACTIVATE" ? "ACTIVE" : "DISABLED" } }); await writeCoreAuditLog({ actorUserId: admin.id, action: `EXTERNAL_LEARNING_COURSE_MAPPING_${body.data.action}D`, subjectType: "ExternalLearningCourseMapping", subjectId: mapping.id, result: "SUCCESS", metadataJson: { providerId: mapping.providerId, status: mapping.status }, ...getRequestAuditContext(request) }); return NextResponse.json({ mapping }); }
