"use client";
import { useState } from "react";
type Comment = { id: string; body: string; status: string; author: { name: string } };
type Post = { id: string; kind: string; body: string; status: string; author: { name: string }; comments: Comment[] };
export function ActivityCommunityClient({ activityId, locale, initialPosts }: { activityId: string; locale: "en" | "zh" | "fr" | "de"; initialPosts: Post[] }) {
  const zh = locale === "zh"; const [posts, setPosts] = useState(initialPosts); const [body, setBody] = useState(""); const [message, setMessage] = useState("");
  const call = async (url: string, payload: object) => { const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const d = await r.json(); if (!r.ok) throw new Error(d.error ?? "Request failed"); return d; };
  async function submit(e: React.FormEvent) { e.preventDefault(); try { const d = await call(`/api/activities/${activityId}/community`, { kind: "DISCUSSION", body }); setPosts([{ ...d.post, author: { name: zh ? "我" : "You" }, comments: [] }, ...posts]); setBody(""); setMessage(zh ? "已提交审核。" : "Submitted for moderation."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to post"); } }
  async function comment(postId: string, value: string, clear: () => void) { try { const d = await call(`/api/activities/${activityId}/community/posts/${postId}/comments`, { body: value }); setPosts(posts.map((p) => p.id === postId ? { ...p, comments: [...p.comments, { ...d.comment, author: { name: zh ? "我" : "You" } }] } : p)); clear(); setMessage(zh ? "评论已提交审核。" : "Comment submitted for moderation."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to comment"); } }
  async function report(postId: string, commentId?: string) { const reason = window.prompt(zh ? "请简要说明举报原因（不含个人信息）" : "Brief report reason (no personal information)"); if (!reason) return; try { await call(`/api/activities/${activityId}/community/posts/${postId}/report`, { reason, commentId }); setMessage(zh ? "举报已提交。" : "Report submitted."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to report"); } }
  return <section className="section"><h2>{zh ? "活动社区" : "Activity community"}</h2><p style={{ color: "var(--color-text-muted)" }}>{zh ? "仅限本活动参与者。内容先审核；请勿发布联系方式或个人信息。" : "For this activity's participants only. Content is premoderated; do not share contact or personal information."}</p><form onSubmit={submit}><textarea value={body} onChange={(e) => setBody(e.target.value)} maxLength={4000} required aria-label={zh ? "讨论内容" : "Discussion"} style={{ width: "100%", minHeight: 80 }} /><button className="button" type="submit">{zh ? "提交讨论" : "Submit discussion"}</button></form>{message && <p role="status">{message}</p>}<div className="list" style={{ marginTop: "1rem" }}>{posts.map((post) => <PostView key={post.id} post={post} zh={zh} onComment={(v, clear) => comment(post.id, v, clear)} onReport={(commentId) => report(post.id, commentId)} />)}</div></section>;
}
function PostView({ post, zh, onComment, onReport }: { post: Post; zh: boolean; onComment: (value: string, clear: () => void) => void; onReport: (commentId?: string) => void }) { const [value, setValue] = useState(""); return <article className="list-item" style={{ display: "block" }}><strong>{post.author.name} · {post.kind}</strong><p style={{ whiteSpace: "pre-wrap" }}>{post.body}</p><button type="button" onClick={() => onReport()}>{zh ? "举报" : "Report"}</button><div style={{ marginLeft: "1rem", marginTop: "0.5rem" }}>{post.comments.map((c) => <p key={c.id}><strong>{c.author.name}:</strong> {c.body} <button type="button" onClick={() => onReport(c.id)}>{zh ? "举报" : "Report"}</button></p>)}<form onSubmit={(e) => { e.preventDefault(); if (value.trim()) onComment(value, () => setValue("")); }}><textarea value={value} onChange={(e) => setValue(e.target.value)} maxLength={4000} required aria-label={zh ? "评论" : "Comment"} style={{ width: "100%", minHeight: 55 }} /><button type="submit">{zh ? "提交评论" : "Submit comment"}</button></form></div></article>; }
