"use client";
import { useCallback, useEffect, useState } from "react";
import { usePromptDialog } from "@/components/prompt-dialog";
import type { Locale } from "@/lib/site-content";
type Draft = { id: string; kind: string; locale: string; status: string; outputJson: any; failureCode: string | null; sourceFieldCount: number; sourceCharacterCount: number };
export function AdminActivityAiContentDrafts({ activityId, locale }: { activityId: string; locale: Locale }) {
  const zh = locale === "zh"; const [drafts, setDrafts] = useState<Draft[]>([]); const [error, setError] = useState(""); const [askPrompt, promptDialog] = usePromptDialog();
  const load = useCallback(() => fetch(`/api/admin/activities/${activityId}/ai-content-drafts`).then((r) => r.json()).then((d) => setDrafts(d.drafts ?? [])), [activityId]);
  useEffect(() => { load(); }, [load]);
  async function request(kind: string, draftLocale: string) { setError(""); const r = await fetch(`/api/admin/activities/${activityId}/ai-content-drafts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, locale: draftLocale }) }); if (!r.ok) setError((await r.json()).error ?? "Request failed"); load(); }
  async function action(draft: Draft, action: string) { setError(""); let outputJson; if (action === "edit") { const raw = await askPrompt({ locale, title: zh ? "编辑草稿内容" : "Edit draft output", description: zh ? "请填写草稿的 JSON 结构，保存后会校验字段格式。" : "Paste the draft JSON; the shape is validated on save.", label: zh ? "JSON 内容" : "JSON output", defaultValue: JSON.stringify(draft.outputJson), multiline: true }); if (!raw) return; try { outputJson = JSON.parse(raw); } catch { setError(zh ? "JSON 格式无效" : "Invalid JSON"); return; } } if (action === "publish" && !window.confirm(zh ? "确认发布已审核文案到公开活动页面？" : "Publish this approved copy to the public activity page?")) return; const r = await fetch(`/api/admin/activities/${activityId}/ai-content-drafts/${draft.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, outputJson }) }); if (!r.ok) setError((await r.json()).error ?? "Request failed"); load(); }
  return <><section className="section"><h2>{zh ? "AI 文案草稿（人工审核）" : "AI copy drafts (human review)"}</h2><p className="compact-note">{zh ? "仅使用活动公开标题、摘要和介绍。生成内容不会自动发布，管理员审核后才能发布。" : "Only public activity title, summary and description are used. Nothing is published automatically; an administrator must review and publish."}</p><div className="button-row">{["SUMMARY", "HIGHLIGHTS", "OVERVIEW_COPY"].map((kind) => ["zh", "en"].map((draftLocale) => <button className="button" key={`${kind}-${draftLocale}`} onClick={() => request(kind, draftLocale)}>{kind} {draftLocale}</button>))}</div>{error && <p className="error-message">{error}</p>}<div className="list">{drafts.map((draft) => <article className="list-item" key={draft.id}><strong>{draft.kind} · {draft.locale} · {draft.status}</strong><p className="compact-note">{zh ? "来源字段" : "Source fields"}: {draft.sourceFieldCount}; {zh ? "字符数" : "characters"}: {draft.sourceCharacterCount}{draft.failureCode ? ` · ${draft.failureCode}` : ""}</p>{draft.outputJson && <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(draft.outputJson, null, 2)}</pre>}<div className="button-row">{["GENERATED", "EDITED"].includes(draft.status) && <><button className="button" onClick={() => action(draft, "edit")}>{zh ? "编辑" : "Edit"}</button><button className="button" onClick={() => action(draft, "approve")}>{zh ? "批准" : "Approve"}</button></>}{draft.status === "APPROVED" && <button className="button" onClick={() => action(draft, "publish")}>{zh ? "确认发布" : "Confirm publish"}</button>}{!["PUBLISHED", "DELETED", "REJECTED"].includes(draft.status) && <button className="button" onClick={() => action(draft, "reject")}>{zh ? "拒绝" : "Reject"}</button>}{draft.status !== "PUBLISHED" && <button className="button" onClick={() => action(draft, "delete")}>{zh ? "删除" : "Delete"}</button>}</div></article>)}</div></section>{promptDialog}</>;
}
