"use client";
import { useEffect, useState } from "react";

const fields = ["name", "title", "dimensions", "evidence"] as const;
type Consent = { mode: "PRIVATE" | "DIRECT_SHARE"; fieldAllowlist: string[]; policyVersion: string };
type Link = { id: string; expiresAt: string; accessCount: number; maxAccessCount: number | null; status: string };

export function PortfolioSharingSettings({ locale }: { locale: "en" | "zh" }) {
  const zh = locale === "zh"; const [consent, setConsent] = useState<Consent>({ mode: "PRIVATE", fieldAllowlist: [], policyVersion: "" }); const [links, setLinks] = useState<Link[]>([]); const [rawToken, setRawToken] = useState<string | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/me/portfolio/consent").then((r) => r.ok ? r.json() : null).then((data) => data && setConsent(data)); fetch("/api/me/portfolio/share-links").then((r) => r.ok ? r.json() : null).then((data) => data?.links && setLinks(data.links)); }, []);
  const toggle = (field: string) => setConsent((value) => ({ ...value, fieldAllowlist: value.fieldAllowlist.includes(field) ? value.fieldAllowlist.filter((x) => x !== field) : [...value.fieldAllowlist, field] }));
  async function save() { const response = await fetch("/api/me/portfolio/consent", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(consent) }); setMessage(response.ok ? (zh ? "分享设置已保存。" : "Sharing settings saved.") : (zh ? "请至少选择一个字段并确认政策版本。" : "Select at least one field and acknowledge the policy version.")); }
  async function create() { setRawToken(null); const response = await fetch("/api/me/portfolio/share-links", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fieldAllowlist: consent.fieldAllowlist, policyVersion: consent.policyVersion, expiresAt: new Date(Date.now() + 7 * 86400000).toISOString(), maxAccessCount: 20 }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to create link."); setRawToken(data.token); setLinks((current) => [{ id: data.id, expiresAt: data.expiresAt, accessCount: data.accessCount, maxAccessCount: data.maxAccessCount, status: data.status }, ...current]); }
  async function revoke(id: string) { const response = await fetch(`/api/me/portfolio/share-links/${encodeURIComponent(id)}`, { method: "DELETE" }); if (response.ok) setLinks((current) => current.map((link) => link.id === id ? { ...link, status: "REVOKED" } : link)); }
  return <section className="mt-8 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">{zh ? "分享与导出" : "Sharing and export"}</h2><p className="mt-2 text-sm text-slate-600">{zh ? "选择分享范围。链接可撤销，令牌只显示一次。" : "Choose the disclosure scope. Links are revocable and the token is shown only once."}</p><fieldset className="mt-4 space-y-2"><legend className="text-sm font-medium">{zh ? "分享模式" : "Sharing mode"}</legend>{(["PRIVATE", "DIRECT_SHARE"] as const).map((mode) => <label className="mr-4 text-sm" key={mode}><input checked={consent.mode === mode} onChange={() => setConsent({ ...consent, mode })} type="radio" name="portfolio-mode" /> {mode}</label>)}</fieldset><div className="mt-4 flex flex-wrap gap-3">{fields.map((field) => <label className="text-sm" key={field}><input disabled={consent.mode === "PRIVATE"} checked={consent.fieldAllowlist.includes(field)} onChange={() => toggle(field)} type="checkbox" /> {field}</label>)}</div><label className="mt-4 block text-sm"><input checked={consent.policyVersion === "portfolio-sharing-v1"} onChange={(event) => setConsent({ ...consent, policyVersion: event.target.checked ? "portfolio-sharing-v1" : "" })} type="checkbox" /> {zh ? "我确认分享政策版本 portfolio-sharing-v1" : "I acknowledge sharing policy version portfolio-sharing-v1"}</label><button className="mt-4 rounded bg-slate-900 px-3 py-2 text-sm text-white" onClick={save} type="button">{zh ? "保存设置" : "Save settings"}</button>{consent.mode === "DIRECT_SHARE" && <button className="ml-3 rounded border px-3 py-2 text-sm" onClick={create} type="button">{zh ? "创建 7 天分享链接" : "Create 7-day share link"}</button>}{rawToken && <p className="mt-4 break-all rounded bg-amber-50 p-3 text-sm">{zh ? "请立即复制此令牌；关闭后不会再次显示：" : "Copy this token now; it will not be shown again:"} {rawToken}</p>}{message && <p className="mt-3 text-sm">{message}</p>}<div className="mt-5 space-y-2">{links.map((link) => <div className="flex items-center justify-between text-sm" key={link.id}><span>{link.status} · {new Date(link.expiresAt).toLocaleDateString()} · {link.accessCount}/{link.maxAccessCount ?? "∞"}</span>{link.status === "ACTIVE" && <button className="underline" onClick={() => revoke(link.id)} type="button">{zh ? "撤销" : "Revoke"}</button>}</div>)}</div><a className="mt-4 inline-block text-sm underline" href="/api/me/portfolio/export">{zh ? "导出 JSON" : "Export JSON"}</a></section>;
}
