import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import ts from 'typescript';
import vm from 'node:vm';
import * as crypto from 'node:crypto';
function load(path,deps={},extras={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:id=>{assert.ok(id in deps,`unexpected import ${id}`);return deps[id]},URL,TextDecoder,...extras});return exports}
const control=load('apps/passport-web/lib/server/auth-mail-worker-control.ts',{'node:crypto':crypto});
const secret='synthetic-worker-secret-32-characters-only';
const req=(body='{}',headers={},url='https://cp.example.invalid/api/internal/auth-mail-worker')=>new Request(url,{method:'POST',headers:{'content-type':'application/json','x-auth-mail-worker-secret':secret,...headers},body});
test('dedicated worker secret required; never cookie/query fallback',()=>{for(const absent of [undefined,'','short','bad secret with whitespace 1234567890'])assert.equal(control.isAuthMailWorkerAuthorized(req(),absent),false);assert.equal(control.isAuthMailWorkerAuthorized(req(),secret),true);assert.equal(control.isAuthMailWorkerAuthorized(req('{}',{'x-auth-mail-worker-secret':'incorrect'}),secret),false);assert.equal(control.isAuthMailWorkerAuthorized(req('{}',{},'https://cp.example.invalid/api/internal/auth-mail-worker?secret='+secret),secret),false);assert.equal(control.isAuthMailWorkerAuthorized(req('{}',{'x-auth-mail-worker-secret':'',cookie:'AUTH_MAIL_WORKER_SECRET='+secret}),secret),false)});
test('batch is auth-only fixed shape, integer one to ten',()=>{assert.equal(control.authMailBatchLimit({}),1);for(const limit of [1,10])assert.equal(control.authMailBatchLimit({limit}),limit);for(const payload of [null,[],{limit:0},{limit:11},{limit:1.5},{limit:'1'},{email:'recipient@example.invalid'},{limit:1,template:'arbitrary'}])assert.equal(control.authMailBatchLimit(payload),null)});
function route(process,env={AUTH_MAIL_WORKER_SECRET:secret}){return load('apps/passport-web/app/api/internal/auth-mail-worker/route.ts',{'next/server':{NextResponse:{json:(body,options={})=>({body,status:options.status??200,headers:options.headers})}},'@/lib/server/auth-mail-worker-control':control,'@/lib/server/auth-mail-outbox':{processAuthMailBatch:process}},{process:{env}})}
test('POST-only worker does not start on import and rejects unauthenticated calls before dispatch',async()=>{let calls=0;const r=route(async()=>{calls++});assert.equal(calls,0);assert.equal(r.GET,undefined);assert.equal((await r.POST(req('{}',{'x-auth-mail-worker-secret':'wrong'}))).status,401);assert.equal(calls,0)});
test('authorized batch dispatches bounded count, hides account/provider metadata',async()=>{let count;const r=route(async n=>{count=n;return{processed:2,email:'private@example.invalid',token:'never-return'}});const response=await r.POST(req('{"limit":2}'));assert.equal(count,2);assert.equal(response.status,200);assert.equal(response.headers['Cache-Control'],'no-store');assert.equal(JSON.stringify(response).includes('private@example.invalid'),false);assert.equal(JSON.stringify(response).includes('never-return'),false)});
test('bad JSON, oversized bodies and arbitrary send payload never invoke worker',async()=>{let calls=0;const r=route(async()=>{calls++});for(const body of ['{','{"limit":999}','{"to":"somebody@example.invalid"}',' '.repeat(257)+'{}'])assert.equal((await r.POST(req(body))).status,400);assert.equal((await r.POST(req('{}',{'content-type':'text/plain'}))).status,415);assert.equal(calls,0)});
test('worker failure sanitized; no retry dispatch',async()=>{let calls=0;const r=route(async()=>{calls++;throw Error('private-token@example.invalid')});const response=await r.POST(req());assert.equal(response.status,503);assert.equal(calls,1);assert.equal(JSON.stringify(response).includes('private-token'),false)});
