import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {PrismaClient} from '@prisma/client';
import {executeGovernance,readGovernance} from '../../apps/passport-web/lib/server/governance';
import {requireGovernanceIssuer} from '../../apps/passport-web/lib/server/governance-credentials';
import {triggerActivityRewards} from '../../apps/passport-web/lib/server/activity-rewards';
import {processActivityRewardDispatch} from '../../apps/passport-web/lib/server/activity-reward-dispatch';
const u=new URL(process.env.DATABASE_URL!);if(u.hostname!=='127.0.0.1'||u.port!=='55432'||u.pathname!=='/cp_governance_test_20261001')throw Error('ONLY_SYNTHETIC_GOVERNANCE_DB_ALLOWED');
const p=new PrismaClient(),run=randomUUID();globalThis.__climatePassportPrisma__=p;const cmd=(actor:string,c:unknown)=>executeGovernance(p,actor,c);const deny=(code:string,fn:()=>Promise<unknown>)=>assert.rejects(fn,(e:any)=>e.code===code);
let ids:any={};
test('governance isolated actual PostgreSQL registry → frozen rules → facts → durable rewards/compensation',async t=>{try{
 const users=await Promise.all(['author','approver','verifier','person','outsider'].map(x=>p.user.create({data:{email:`gov-${run}-${x}@example.invalid`,password:'!no-login-synthetic',name:x,role:x==='outsider'?'ADMIN':'ATTENDEE'}})));const [author,approver,verifier,person,outsider]=users;ids.users=users.map(x=>x.id);
 const tenant=await p.tenant.create({data:{key:'GOV_'+run,name:'Synthetic tenant'}});ids.tenant=tenant.id;const programme=await p.programme.create({data:{tenantId:tenant.id,key:'GOV_'+run,name:'Synthetic Programme'}});ids.programme=programme.id;
 const institution=await p.institution.create({data:{slug:'gov-'+run,name:'Synthetic issuer'}});ids.institution=institution.id;
 await p.accessMembership.createMany({data:[{userId:author.id,programmeId:programme.id,role:'PROGRAMME_ADMIN'},{userId:approver.id,programmeId:programme.id,role:'PROGRAMME_ADMIN'},{userId:verifier.id,programmeId:programme.id,role:'PROGRAMME_OPERATOR'}]});await p.institutionRepresentation.create({data:{institutionId:institution.id,userId:author.id,programmeId:programme.id,actionScope:['MANAGE']}});
 const registered:any=await cmd(author.id,{action:'register',programmeId:programme.id,institutionId:institution.id,kind:'learning_unit',title:'Synthetic GCA course and FS sample'});const project=registered.project;ids.project=project.id;
 await t.test('technical ADMIN has no programme access; self-approval is denied',async()=>{await deny('GOV_SCOPE_DENIED',()=>readGovernance(p,outsider.id,project.id));await deny('GOV_SEPARATION_OF_DUTIES',()=>cmd(author.id,{action:'transition',projectId:project.id,transition:'approve'}));});
 await t.test('edition-only institution representation never authorizes a whole Programme governance project or issuer',async()=>{
  const edition=await p.edition.create({data:{programmeId:programme.id,key:'EDITION_'+run,name:'Synthetic limited edition'}});
  const rep=await p.institutionRepresentation.findFirstOrThrow({where:{institutionId:institution.id,userId:author.id}});
  await p.institutionRepresentation.update({where:{id:rep.id},data:{editionId:edition.id}});
  try{
   await deny('GOV_INSTITUTION_DENIED',()=>cmd(author.id,{action:'register',programmeId:programme.id,institutionId:institution.id,kind:'learning_unit',title:'Must not widen edition authority'}));
   await assert.rejects(p.$transaction(tx=>requireGovernanceIssuer(tx,author.id,institution.id,programme.id,new Date())),/GOV_ISSUER_DENIED/);
  }finally{await p.institutionRepresentation.update({where:{id:rep.id},data:{editionId:null}});}
 });
 await t.test('legacy ACTIVE uniqueness is preserved and foreign programme binding blocks registration',async()=>{const other=await p.programme.create({data:{tenantId:tenant.id,key:'OTHER_'+run,name:'Other synthetic scope'}});const a=await p.activity.create({data:{type:'EVENT',slug:'multi-'+run,title:'Multi source synthetic',createdByUserId:author.id,organizerUserId:author.id}});const existing=await p.sourceObjectMapping.create({data:{programmeId:programme.id,activityId:a.id,sourceSystem:'first-'+run,sourceObjectId:'a'}});await assert.rejects(()=>p.sourceObjectMapping.create({data:{programmeId:other.id,activityId:a.id,sourceSystem:'second-'+run,sourceObjectId:'b'}}));await p.sourceObjectMapping.update({where:{id:existing.id},data:{programmeId:other.id}});await deny('GOV_SCOPE_DENIED',()=>cmd(author.id,{action:'register',programmeId:programme.id,institutionId:institution.id,activityId:a.id,kind:'activity',title:'Cross scope should fail'}));});
 const sources:any[]=[];for(const app of ['gca','fs']){
 // Synthetic USER_FACING metadata only: no machine credential, scope or external network.
 const client=await p.channelClient.create({data:{key:'GOV_'+app+'_'+run,displayName:'Synthetic registered metadata',type:'USER_FACING',programmeId:programme.id,allowedScopes:[],allowedOrigins:[],allowedIps:[]}});
 const out:any=await cmd(author.id,{action:'source',projectId:project.id,channelClientId:client.id,sourceApp:app,sourceAuthority:'synthetic:'+app,externalUnitId:app+'-unit-'+run,issuer:'https://synthetic.invalid',rpAudience:'synthetic:'+app,verifierUserId:verifier.id});sources.push(out.source);
 }
 await cmd(approver.id,{action:'transition',projectId:project.id,transition:'approve'});await cmd(approver.id,{action:'transition',projectId:project.id,transition:'publish'});
 await t.test('one canonical project has two source mappings; published source config is frozen',async()=>{assert.equal(await p.governanceSource.count({where:{projectId:project.id}}),2);await deny('GOV_FROZEN',()=>cmd(author.id,{action:'source',projectId:project.id,channelClientId:sources[0].channelClientId,sourceApp:'gca',sourceAuthority:'spoof',externalUnitId:'spoof',issuer:'https://synthetic.invalid',rpAudience:'synthetic',verifierUserId:verifier.id}));});
 const now=new Date();const ruleBody={action:'rule',projectId:project.id,version:1,condition:{schemaVersion:'cp-condition/1',all:[{field:'verificationLevel',op:'eq',value:'source_verified'},{field:'score',op:'gte',value:50}]},rewards:[{type:'POINTS',points:5}],validFrom:new Date(now.getTime()-10000).toISOString(),validUntil:new Date(now.getTime()+86400000).toISOString()};const out:any=await cmd(author.id,ruleBody);const rule=out.rule;ids.rule=rule.id;
 await t.test('unapproved rule cannot be published; separate approval precedes publication',async()=>{await deny('GOV_STATE_CONFLICT',()=>cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:rule.id,transition:'publish'}));await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:rule.id,transition:'approve'});await assert.rejects(()=>p.governanceRuleVersion.update({where:{id:rule.id},data:{rewardsJson:[{type:'POINTS',points:999}]}}));await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:rule.id,transition:'publish'});});
 const fixtures:any[]=[];for(const source of sources){const record='new-synthetic-'+source.sourceApp+'-'+run;const b:any=await cmd(approver.id,{action:'binding',sourceId:source.id,ruleVersionId:rule.id,userId:person.id,subject:'synthetic-person',sourceRecordId:record,verificationRef:'explicit-synthetic-test-identity-proof'});const at=new Date();const consent=await p.consentRecord.create({data:{subjectUserId:person.id,grantorUserId:person.id,purpose:'reward_qualification',channel:source.sourceApp,objectType:'governance_outcome',objectId:record,createdAt:at,validFrom:at}});const archive=await p.consentRecord.create({data:{subjectUserId:person.id,grantorUserId:person.id,purpose:'private_archive',channel:source.sourceApp,objectType:'governance_outcome',objectId:record,createdAt:at,validFrom:at}});fixtures.push({source,binding:b.binding,consent,archive,event:{schemaVersion:'cp-governance/1',eventId:'event-'+randomUUID(),bindingId:b.binding.id,ruleVersionId:rule.id,identity:{issuer:source.issuer,subject:'synthetic-person'},sourceRecord:{id:record,version:1},operation:'upsert',occurredAt:new Date(Date.now()+1).toISOString(),consent:{receiptId:consent.id,version:consent.version,scope:'reward_qualification',grantedAt:at.toISOString()},data:{kind:source.sourceApp==='gca'?'learning_completion':'approved_private_evidence',status:source.sourceApp==='gca'?'completed':'accepted',verificationLevel:'source_verified',score:60,evidenceRefs:['synthetic-evidence']}}});}
 const g=fixtures[0],f=fixtures[1];
 await t.test('rule version is frozen at entry before any first source fact',async()=>{const next:any=await cmd(author.id,{...ruleBody,version:2});await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:next.rule.id,transition:'approve'});await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:next.rule.id,transition:'publish'});await deny('GOV_PARTICIPATION_RULE_PINNED',()=>cmd(approver.id,{action:'binding',sourceId:sources[0].id,ruleVersionId:next.rule.id,userId:person.id,subject:'synthetic-person',sourceRecordId:'before-first-fact-'+run,verificationRef:'synthetic'}));assert.equal(await p.governanceFact.count({where:{bindingId:g.binding.id}}),0);});
 await t.test('exact verified binding and current distinct-purpose consent are required',async()=>{await deny('GOV_BINDING_DENIED',()=>cmd(verifier.id,{action:'qualify',event:{...g.event,identity:{...g.event.identity,subject:'wrong'}}}));await deny('GOV_CONSENT_DENIED',()=>cmd(verifier.id,{action:'qualify',event:{...g.event,consent:{...g.event.consent,receiptId:g.archive.id}}}));});
 await t.test('source client programme reassignment blocks new qualification',async()=>{const other=await p.programme.create({data:{tenantId:tenant.id,key:'REASSIGN_'+run,name:'Synthetic other'}});await p.channelClient.update({where:{id:g.source.channelClientId},data:{programmeId:other.id}});try{await deny('GOV_SOURCE_DENIED',()=>cmd(verifier.id,{action:'qualify',event:g.event}));assert.equal(await p.governanceFact.count({where:{bindingId:g.binding.id}}),0);}finally{await p.channelClient.update({where:{id:g.source.channelClientId},data:{programmeId:programme.id}});}});
 const accepted:any=await cmd(verifier.id,{action:'qualify',event:g.event});
 await t.test('concurrent duplicate facts have one outbox; receipt is not reward success',async()=>{assert.equal(accepted.rewardSuccess,false);const results:any[]=await Promise.all(Array.from({length:6},()=>cmd(verifier.id,{action:'qualify',event:g.event})));assert.ok(results.every(x=>x.factId===accepted.factId));assert.equal(await p.governanceRewardTask.count({where:{factId:accepted.factId}}),1);assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,0);await deny('GOV_IMMUTABLE_CONFLICT',()=>cmd(verifier.id,{action:'qualify',event:{...g.event,data:{...g.event.data,score:70}}}));});
 const task=await p.governanceRewardTask.findFirstOrThrow({where:{factId:accepted.factId}});
 await t.test('transaction failure persists retry with no partial award; later retry succeeds once',async()=>{
 await p.$executeRawUnsafe(`CREATE FUNCTION gov_synthetic_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.type='GOVERNANCE_REWARD' THEN RAISE EXCEPTION 'synthetic_fault'; END IF; RETURN NEW; END $$`);await p.$executeRawUnsafe('CREATE TRIGGER gov_test_fail BEFORE INSERT ON point_transactions FOR EACH ROW EXECUTE FUNCTION gov_synthetic_failure()');
 try{await deny('GOV_REWARD_RETRY',()=>cmd(approver.id,{action:'process',projectId:project.id,taskId:task.id}));assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,0);assert.equal(await p.governanceRewardGrant.count({where:{factId:accepted.factId}}),0);assert.equal((await p.governanceRewardTask.findUniqueOrThrow({where:{id:task.id}})).state,'RETRY');}finally{await p.$executeRawUnsafe('DROP TRIGGER gov_test_fail ON point_transactions');await p.$executeRawUnsafe('DROP FUNCTION gov_synthetic_failure()');}
 await cmd(approver.id,{action:'retry',projectId:project.id,taskId:task.id});await Promise.all(Array.from({length:6},()=>cmd(approver.id,{action:'process',projectId:project.id,taskId:task.id})));assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);assert.equal(await p.pointTransaction.count({where:{userId:person.id,type:'GOVERNANCE_REWARD'}}),1);
 });
 await t.test('archive consent withdrawal preserves independent qualification and awarded points',async()=>{await p.consentRecord.update({where:{id:g.archive.id},data:{status:'WITHDRAWN'}});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);assert.equal((await p.governanceFact.findUniqueOrThrow({where:{id:accepted.factId}})).state,'ELIGIBLE');});
 let corrected:any;
 await t.test('two sources for one canonical participation never produce two rewards',async()=>{assert.equal(g.binding.participationId,f.binding.participationId);const second:any=await cmd(verifier.id,{action:'qualify',event:f.event});f.accepted=second;const tt=await p.governanceRewardTask.findFirstOrThrow({where:{factId:second.factId}});await cmd(approver.id,{action:'process',projectId:project.id,taskId:tt.id});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);assert.equal(await p.governanceRewardGrant.count({where:{userId:person.id,type:'POINTS'}}),1);assert.equal(await p.governanceRewardDecision.count({where:{participationId:g.binding.participationId,type:'POINTS',state:'ACTIVE'}}),1);});
 await t.test('eligible correction updates evidence basis without re-awarding the canonical prize',async()=>{const e={...g.event,eventId:'correct-'+randomUUID(),operation:'correct',supersedesEventId:g.event.eventId,sourceRecord:{...g.event.sourceRecord,version:2},occurredAt:new Date().toISOString(),data:{...g.event.data,score:80}};corrected=await cmd(verifier.id,{action:'qualify',event:e});g.correct=e;const nt=await p.governanceRewardTask.findFirstOrThrow({where:{factId:corrected.factId,operation:'GRANT'}});await cmd(approver.id,{action:'process',projectId:project.id,taskId:nt.id});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);assert.equal(await p.pointTransaction.count({where:{userId:person.id,type:'GOVERNANCE_REWARD'}}),1);});
 await t.test('revoking one source preserves the award while another valid source basis remains',async()=>{await p.consentRecord.update({where:{id:g.consent.id},data:{status:'WITHDRAWN'}});const {consent,data,...minimal}=g.correct;const e={...minimal,eventId:'revoke-'+randomUUID(),operation:'revoke',supersedesEventId:g.correct.eventId,sourceRecord:{...g.event.sourceRecord,version:3},occurredAt:new Date().toISOString()};await cmd(verifier.id,{action:'qualify',event:e});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);const d=await p.governanceRewardDecision.findUniqueOrThrow({where:{participationId_type:{participationId:g.binding.participationId,type:'POINTS'}}});assert.equal(d.state,'ACTIVE');assert.equal(d.basisFactId,f.accepted.factId);assert.equal(await p.pointTransaction.count({where:{userId:person.id,type:'GOVERNANCE_REVERSAL'}}),0);});
 await t.test('loss of the last eligible basis compensates once; later valid correction may restore one prize',async()=>{const low={...f.event,eventId:'fs-correct-'+randomUUID(),operation:'correct',supersedesEventId:f.event.eventId,sourceRecord:{...f.event.sourceRecord,version:2},occurredAt:new Date().toISOString(),data:{...f.event.data,score:40}};const no:any=await cmd(verifier.id,{action:'qualify',event:low});assert.equal(no.eligibility,'ineligible');const rt=await p.governanceRewardTask.findFirstOrThrow({where:{factId:accepted.factId,operation:'REVERSE'}});await Promise.all(Array.from({length:4},()=>cmd(approver.id,{action:'process',projectId:project.id,taskId:rt.id})));assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,0);assert.equal(await p.pointTransaction.count({where:{userId:person.id,type:'GOVERNANCE_REVERSAL'}}),1);const high={...low,eventId:'fs-restore-'+randomUUID(),supersedesEventId:low.eventId,sourceRecord:{...low.sourceRecord,version:3},occurredAt:new Date().toISOString(),data:{...low.data,score:60}};f.correct=high;const yes:any=await cmd(verifier.id,{action:'qualify',event:high});const tt=await p.governanceRewardTask.findFirstOrThrow({where:{factId:yes.factId}});await cmd(approver.id,{action:'process',projectId:project.id,taskId:tt.id});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);});
 await t.test('withdrawn qualification consent blocks pending grants, never rewrites prior valid grants',async()=>{const pendingPerson=await p.user.create({data:{email:'pending-'+run+'@example.invalid',password:'!no-login',name:'Pending synthetic person'}});const source=sources[0],record='pending-'+run;const b:any=await cmd(approver.id,{action:'binding',sourceId:source.id,ruleVersionId:rule.id,userId:pendingPerson.id,subject:'synthetic-person',sourceRecordId:record,verificationRef:'synthetic-verified'});const at=new Date();const consent=await p.consentRecord.create({data:{subjectUserId:pendingPerson.id,grantorUserId:pendingPerson.id,purpose:'reward_qualification',channel:'gca',objectType:'governance_outcome',objectId:record,createdAt:at,validFrom:at}});const e={...g.event,eventId:'pending-'+randomUUID(),bindingId:b.binding.id,sourceRecord:{id:record,version:1},occurredAt:new Date().toISOString(),consent:{receiptId:consent.id,version:1,scope:'reward_qualification',grantedAt:at.toISOString()}};const q:any=await cmd(verifier.id,{action:'qualify',event:e});await p.consentRecord.update({where:{id:consent.id},data:{status:'WITHDRAWN'}});const tt=await p.governanceRewardTask.findFirstOrThrow({where:{factId:q.factId}});const r:any=await cmd(approver.id,{action:'process',projectId:project.id,taskId:tt.id});assert.equal(r.state,'BLOCKED');assert.equal(r.failureCode,'QUALIFICATION_CONSENT_WITHDRAWN');assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,5);});
 await t.test('legacy conditions fail closed, supported empty rules award once and persist blocked unsupported rewards',async()=>{
 const activity=await p.activity.create({data:{type:'EVENT',slug:'gov-'+run,title:'Synthetic legacy activity',createdByUserId:author.id,organizerUserId:author.id}});ids.activity=activity.id;
 await p.activityRewardRule.createMany({data:[{activityId:activity.id,trigger:'CHECKIN_COMPLETED',rewardType:'POINTS',rewardValueJson:{points:2},conditionJson:{script:'arbitrary'}},{activityId:activity.id,trigger:'CHECKIN_COMPLETED',rewardType:'POINTS',rewardValueJson:{points:3}},{activityId:activity.id,trigger:'CHECKIN_COMPLETED',rewardType:'CERTIFICATE',rewardValueJson:{definitionId:'unsupported'}}]});
 await Promise.all(Array.from({length:4},()=>triggerActivityRewards({activityId:activity.id,userId:person.id,trigger:'CHECKIN_COMPLETED'})));const jobs=await p.activityRewardDispatch.findMany({where:{activityId:activity.id}});assert.equal(jobs.filter(x=>x.state==='SUCCEEDED').length,1);assert.equal(jobs.filter(x=>x.state==='BLOCKED').length,2);assert.equal(await p.pointTransaction.count({where:{userId:person.id,type:'ACTIVITY_REWARD'}}),1);assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,8);
 });
 await t.test('legacy previously awarded points badge and milestone are not re-issued after upgrade',async()=>{const a=await p.activity.create({data:{type:'EVENT',slug:'legacy-old-'+run,title:'Old synthetic activity',createdByUserId:author.id,organizerUserId:author.id}});const badge=await p.badgeDefinition.create({data:{code:'OLD_'+run,name:'Old synthetic badge',category:'PARTICIPATION'}});const rules=[];for(const [type,val] of [['POINTS',{points:2}],['BADGE',{badgeDefinitionId:badge.id}],['PASSPORT_ENTRY',{}]] as const)rules.push(await p.activityRewardRule.create({data:{activityId:a.id,trigger:'CHECKIN_COMPLETED',rewardType:type,rewardValueJson:val}}));await p.pointTransaction.create({data:{userId:person.id,type:'ACTIVITY_REWARD',points:2,description:`[reward:${rules[0].id}:${person.id}] 活动奖励 — Old synthetic activity`}});await p.user.update({where:{id:person.id},data:{points:{increment:2}}});await p.badgeAward.create({data:{userId:person.id,badgeDefinitionId:badge.id,evidenceSnapshotJson:{rewardRuleId:rules[1].id,activityId:a.id}}});await p.passportMilestone.create({data:{userId:person.id,activityId:a.id,title:a.title,sourceType:'ACTIVITY_REWARD',sourceId:rules[2].id}});const before=(await p.user.findUniqueOrThrow({where:{id:person.id}})).points;await triggerActivityRewards({activityId:a.id,userId:person.id,trigger:'CHECKIN_COMPLETED'});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,before);assert.equal(await p.badgeAward.count({where:{userId:person.id,badgeDefinitionId:badge.id}}),1);assert.equal(await p.passportMilestone.count({where:{userId:person.id,activityId:a.id,sourceType:'ACTIVITY_REWARD'}}),1);assert.equal(await p.activityRewardDispatch.count({where:{activityId:a.id,state:'SUCCEEDED'}}),3);});
 await t.test('participation freezes its rule before any first fact; retired version accepts historical correction',async()=>{const other:any=await cmd(author.id,{...ruleBody,version:3});await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:other.rule.id,transition:'approve'});await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:other.rule.id,transition:'publish'});await deny('GOV_PARTICIPATION_RULE_PINNED',()=>cmd(approver.id,{action:'binding',sourceId:sources[0].id,ruleVersionId:other.rule.id,userId:person.id,subject:'synthetic-person',sourceRecordId:'not-new-rule-'+run,verificationRef:'synthetic-proof'}));await cmd(approver.id,{action:'transition',projectId:project.id,ruleVersionId:rule.id,transition:'retire'});const newcomer=await p.user.create({data:{email:'newcomer-'+run+'@example.invalid',password:'!no-login',name:'Synthetic newcomer'}});await deny('GOV_RULE_NOT_EFFECTIVE',()=>cmd(approver.id,{action:'binding',sourceId:sources[0].id,ruleVersionId:rule.id,userId:newcomer.id,subject:'new-person',sourceRecordId:'retired-entry-'+run,verificationRef:'synthetic-proof'}));const historic={...f.correct,eventId:'historic-'+randomUUID(),supersedesEventId:f.correct.eventId,sourceRecord:{...f.correct.sourceRecord,version:4},occurredAt:new Date().toISOString(),data:{...f.correct.data,score:70}};const yes:any=await cmd(verifier.id,{action:'qualify',event:historic});assert.equal(yes.eligibility,'eligible');const tt=await p.governanceRewardTask.findFirstOrThrow({where:{factId:yes.factId}});await cmd(approver.id,{action:'process',projectId:project.id,taskId:tt.id});assert.equal((await p.user.findUniqueOrThrow({where:{id:person.id}})).points,10);});
 await t.test('credential issuer authorization and true PDF issuance are controlled by frozen rule snapshots',async()=>{
 await p.institutionRepresentation.create({data:{institutionId:institution.id,userId:approver.id,programmeId:programme.id,actionScope:['MANAGE']}});
 const badge=await p.badgeDefinition.create({data:{code:'CREDENTIAL_'+run,name:'Synthetic learning badge',category:'LEARNING',issuerName:'Mutable old display'}});
 const category=await p.certificateCategory.create({data:{key:'CREDENTIAL_'+run,name:'Synthetic credential category',pdfEnabled:true}});
 const template=await p.certificateTemplate.create({data:{categoryId:category.id,name:'Synthetic self-contained template',templateType:'LEARNING',templateConfigJson:{},renderConfigJson:{issuerName:'Untrusted template display',pageSize:'A4_LANDSCAPE'},version:1}});
 const definition=await p.certificateDefinition.create({data:{categoryId:category.id,templateId:template.id,name:'Synthetic completion certificate',approvalMode:'auto'}});
 const registered:any=await cmd(author.id,{action:'register',programmeId:programme.id,institutionId:institution.id,kind:'learning_unit',title:'Credential synthetic learning unit'});const unit=registered.project;
 const client=await p.channelClient.create({data:{key:'CRED_'+run,displayName:'Synthetic credential source metadata',type:'USER_FACING',programmeId:programme.id,allowedScopes:[],allowedOrigins:[],allowedIps:[]}});
 const out:any=await cmd(author.id,{action:'source',projectId:unit.id,channelClientId:client.id,sourceApp:'gca',sourceAuthority:'synthetic:gca:credential',externalUnitId:'credential-unit-'+run,issuer:'https://synthetic.invalid',rpAudience:'synthetic:gca:credential',verifierUserId:verifier.id});const source=out.source;
 await cmd(approver.id,{action:'transition',projectId:unit.id,transition:'approve'});await cmd(approver.id,{action:'transition',projectId:unit.id,transition:'publish'});
 const body={...ruleBody,projectId:unit.id,version:1,rewards:[{type:'BADGE',badgeDefinitionId:badge.id,issuerInstitutionId:institution.id,credentialClass:'completion'},{type:'CERTIFICATE',certificateDefinitionId:definition.id,issuerInstitutionId:institution.id,credentialClass:'completion'}]};
 await deny('GOV_ISSUER_DENIED',()=>cmd(verifier.id,body));await deny('GOV_ISSUER_DENIED',()=>cmd(author.id,{...body,rewards:[{...body.rewards[0],issuerInstitutionId:randomUUID()}]}));
 const ro:any=await cmd(author.id,body);const cr=ro.rule;await cmd(approver.id,{action:'transition',projectId:unit.id,ruleVersionId:cr.id,transition:'approve'});await cmd(approver.id,{action:'transition',projectId:unit.id,ruleVersionId:cr.id,transition:'publish'});
 // The mutable original template is not allowed to reinterpret the published rule.
 await p.certificateTemplate.update({where:{id:template.id},data:{version:2,renderConfigJson:{issuerName:'Changed later',pageSize:'A4_PORTRAIT'}}});
 const holder=await p.user.create({data:{email:'credential-holder-'+run+'@example.invalid',password:'!no-login',name:'Synthetic 学习参与者'}});
 const record='credential-record-'+run;const bo:any=await cmd(approver.id,{action:'binding',sourceId:source.id,ruleVersionId:cr.id,userId:holder.id,subject:'credential-person',sourceRecordId:record,verificationRef:'explicit-synthetic-credential-proof'});const at=new Date();const consent=await p.consentRecord.create({data:{subjectUserId:holder.id,grantorUserId:holder.id,purpose:'reward_qualification',channel:'gca',objectType:'governance_outcome',objectId:record,createdAt:at,validFrom:at}});
 const event={...g.event,eventId:'credential-'+randomUUID(),bindingId:bo.binding.id,ruleVersionId:cr.id,identity:{issuer:source.issuer,subject:'credential-person'},sourceRecord:{id:record,version:1},occurredAt:new Date().toISOString(),consent:{receiptId:consent.id,version:1,scope:'reward_qualification',grantedAt:at.toISOString()},data:{...g.event.data,score:75}};
 const accepted:any=await cmd(verifier.id,{action:'qualify',event});const tasks=await p.governanceRewardTask.findMany({where:{factId:accepted.factId}});assert.equal(tasks.length,2);assert.equal((await p.user.findUniqueOrThrow({where:{id:holder.id}})).points,0);
 for(const tt of tasks)await Promise.all([cmd(approver.id,{action:'process',projectId:unit.id,taskId:tt.id}),cmd(approver.id,{action:'process',projectId:unit.id,taskId:tt.id})]);
 const grants=await p.governanceRewardGrant.findMany({where:{userId:holder.id}});assert.equal(grants.length,2);const bg=grants.find(x=>x.type==='BADGE')!,cg=grants.find(x=>x.type==='CERTIFICATE')!;
 const ba=await p.badgeAward.findUniqueOrThrow({where:{id:bg.badgeAwardId!}});assert.equal(ba.awardedByOrgName,institution.name);assert.equal(ba.verificationToken,null);
 const issue=await p.certificateIssue.findUniqueOrThrow({where:{id:cg.certificateIssueId!}});assert.equal(issue.status,'ISSUED');assert.equal(issue.artifactState,'READY');assert.equal(issue.artifactContentType,'application/pdf');assert.ok(issue.artifactByteSize!>1000);assert.equal(issue.publicVisible,false);assert.equal((issue.renderSnapshotJson as any).templateVersion,1);assert.equal((issue.renderSnapshotJson as any).issuerName,institution.name);assert.equal((issue.renderSnapshotJson as any).credentialClass,'completion');
 await deny('GOV_OWNER_DENIED',()=>cmd(outsider.id,{action:'visibility',grantId:bg.id,publicVisible:true}));await cmd(holder.id,{action:'visibility',grantId:bg.id,publicVisible:true});assert.ok((await p.badgeAward.findUniqueOrThrow({where:{id:bg.badgeAwardId!}})).verificationToken);await cmd(holder.id,{action:'visibility',grantId:bg.id,publicVisible:false});assert.equal((await p.badgeAward.findUniqueOrThrow({where:{id:bg.badgeAwardId!}})).status,'ACTIVE');await cmd(holder.id,{action:'visibility',grantId:cg.id,publicVisible:true});await cmd(holder.id,{action:'visibility',grantId:cg.id,publicVisible:false});assert.equal((await p.certificateIssue.findUniqueOrThrow({where:{id:cg.certificateIssueId!}})).status,'ISSUED');
 const {consent:unused,data,...minimal}=event;await cmd(verifier.id,{action:'qualify',event:{...minimal,eventId:'credential-revoke-'+randomUUID(),operation:'revoke',supersedesEventId:event.eventId,sourceRecord:{id:record,version:2},occurredAt:new Date().toISOString()}});
 const reversals=await p.governanceRewardTask.findMany({where:{factId:accepted.factId,operation:'REVERSE'}});assert.equal(reversals.length,2);for(const tt of reversals)await Promise.all([cmd(approver.id,{action:'process',projectId:unit.id,taskId:tt.id}),cmd(approver.id,{action:'process',projectId:unit.id,taskId:tt.id})]);assert.equal((await p.badgeAward.findUniqueOrThrow({where:{id:bg.badgeAwardId!}})).status,'REVOKED');assert.equal((await p.certificateIssue.findUniqueOrThrow({where:{id:cg.certificateIssueId!}})).status,'REVOKED');await deny('GOV_FACT_INVALIDATED',()=>cmd(holder.id,{action:'visibility',grantId:cg.id,publicVisible:true}));
 });
 }finally{await p.$disconnect();}});
