import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/server/auth";
import { applicationEligibilityWhere } from "@/lib/server/certificate-applications";
import { getPrismaClient } from "@/lib/server/prisma";
const patchSchema = z.object({ statement: z.string().trim().max(4000).optional(), sourceType: z.string().trim().max(80).optional(), sourceId: z.string().trim().max(160).optional(), sourceLabel: z.string().trim().max(240).optional(), submit: z.boolean().optional() });
async function owner(id: string) { const user = await getCurrentUser(); const prisma = getPrismaClient(); if (!user || !prisma) return { user, prisma, application: null }; const application = await prisma.certificateApplication.findFirst({ where: { id, applicantId: user.id }, include: { definition: { include: { category: true } }, events: { orderBy: { createdAt: "asc" } }, certificateIssue: true } }); return { user, prisma, application }; }
export async function GET(_: Request, { params }: { params: { id: string } }) { const result = await owner(params.id); if (!result.user) return NextResponse.json({ error: "Authentication required." }, { status: 401 }); if (!result.prisma) return NextResponse.json({ error: "Database unavailable." }, { status: 503 }); if (!result.application) return NextResponse.json({ error: "Application not found." }, { status: 404 }); return NextResponse.json({ application: result.application }); }
export async function PATCH(request: Request, { params }: { params: { id: string } }) { const result = await owner(params.id); if (!result.user) return NextResponse.json({ error: "Authentication required." }, { status: 401 }); if (!result.prisma) return NextResponse.json({ error: "Database unavailable." }, { status: 503 }); if (!result.application) return NextResponse.json({ error: "Application not found." }, { status: 404 }); if (!(["DRAFT", "NEEDS_INFORMATION"] as string[]).includes(result.application.status)) return NextResponse.json({ error: "This application cannot be edited." }, { status: 409 }); const parsed = patchSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid request." }, { status: 400 }); const value = parsed.data; if (value.submit) { const eligible = await result.prisma.certificateDefinition.findFirst({ where: applicationEligibilityWhere(result.application.definitionId), select: { id: true } }); if (!eligible) return NextResponse.json({ error: "Certificate definition is no longer available for requests." }, { status: 409 }); } const toStatus = value.submit ? "SUBMITTED" : result.application.status; const application = await result.prisma.$transaction(async (tx) => { const updated = await tx.certificateApplication.update({ where: { id: params.id }, data: { statement: value.statement ?? result.application!.statement, sourceType: value.sourceType ?? result.application!.sourceType, sourceId: value.sourceId ?? result.application!.sourceId, sourceLabel: value.sourceLabel ?? result.application!.sourceLabel, status: toStatus, submittedAt: value.submit ? new Date() : result.application!.submittedAt, applicantMessage: value.submit ? null : result.application!.applicantMessage } }); if (value.submit) await tx.certificateApplicationEvent.create({ data: { applicationId: params.id, actorUserId: result.user!.id, fromStatus: result.application!.status, toStatus: "SUBMITTED", kind: "SUBMIT" } }); return updated; }); return NextResponse.json({ application }); }
